sudo: required
dist: trusty
language:  java
jdk: oraclejdk8
env:
  GOPATH=$TRAVIS_BUILD_DIR
  VDLPATH=$GOPATH/src
  VANADIUM_CORE_REPO=$TRAVIS_BUILD_DIR

before_install:
  - GIMME_OUTPUT=$(gimme 1.11.1) && eval "$GIMME_OUTPUT"
  - mkdir $TRAVIS_BUILD_DIR/src

install:
  - echo "GOPATH:" $GOPATH
  - echo "VDLPATH:" $VDLPATH
  - go get -t v.io/... 
  - go install v.io/...

script:
  - make java
  - make java-test
 
notifications:
    email: false
